name: jarvis_offline
description: Jarvis Offline V2
version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.0
  flutter_local_notifications: ^17.0.0

flutter:
  uses-material-design: true